"""
Local Markdown search engine with hybrid keyword + semantic reranking.

This module provides:
- Recursive loading of .md files from a directory
- Fast keyword filtering with contextual excerpt extraction
- Semantic reranking using SentenceTransformer embeddings
- In-memory embedding cache for performance

Used by LangGraph agents to perform local RAG-style search over documentation.
"""

__all__ = ["load_markdown_files", "search_markdown"]


import os
import pathlib
import logging
import numpy as np

from typing import List, Dict

from sentence_transformers import SentenceTransformer

os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["TRANSFORMERS_VERBOSITY"] = "error"
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

logging.getLogger("sentence_transformers").setLevel(logging.ERROR)
logging.getLogger("transformers").setLevel(logging.ERROR)
logging.getLogger("huggingface_hub").setLevel(logging.ERROR)

_embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
_embedding_cache: Dict[str, np.ndarray] = {}


EXCERPT_BEFORE = 100
EXCERPT_TOTAL = 400


def semantic_rerank(
    query: str, results: List[Dict], corpus: List[Dict], top_k: int = 5
) -> List[Dict]:
    """
    Rerank keyword-filtered results using semantic similarity.

    Parameters
    ----------
    query : str
        The original search query.
    results : List[Dict]
        Keyword-filtered results.
    top_k : int
        Number of top results to return.

    Returns
    -------
    List[Dict]
        Reranked list of results.
    """
    if not results:
        return results

    query_emb = get_embedding(query)

    scored = []
    for r in results:
        full_doc = next(
            (doc["content"] for doc in corpus if doc["path"] == r["source"]), None
        )
        if full_doc is None:
            continue

        doc_emb = get_embedding(full_doc)

        score = np.dot(query_emb, doc_emb) / (
            np.linalg.norm(query_emb) * np.linalg.norm(doc_emb)
        )
        scored.append((score, r))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [r for _, r in scored[:top_k]]


def get_embedding(text: str) -> np.ndarray:
    """
    Compute or retrieve a cached embedding for a given text.

    This function uses a lightweight SentenceTransformer model to generate
    semantic embeddings. Results are cached in memory to avoid recomputation
    and significantly speed up repeated searches.

    Parameters
    ----------
    text : str
        The text to embed.

    Returns
    -------
    np.ndarray
        The embedding vector for the given text.
    """
    if text in _embedding_cache:
        return _embedding_cache[text]

    emb = _embedding_model.encode(text, convert_to_numpy=True)
    _embedding_cache[text] = emb
    return emb


def load_markdown_files(base_dir: str) -> List[Dict]:
    """
    Recursively load all Markdown (.md) files from a directory.

    Each file is read into memory and stored as a dictionary containing:
        - "path": full file path
        - "content": raw text content

    Parameters
    ----------
    base_dir : str
        Path to the directory containing Markdown documentation.

    Returns
    -------
    List[Dict]
        A list of dictionaries representing Markdown files.

    Raises
    ------
    ValueError
        If the directory does not exist or is not a directory.
    """
    base_path = pathlib.Path(base_dir)

    if not base_path.exists() or not base_path.is_dir():
        raise ValueError(f"Directory does not exist: {base_dir}")

    files: List[Dict] = []
    for md_file in base_path.rglob("*.md"):
        try:
            content = md_file.read_text(encoding="utf-8")
            files.append({"path": str(md_file), "content": content})
        except Exception as e:
            logging.warning(f"Failed to read {md_file}: {e}")
            continue

    return files


def search_markdown(
    query: str,
    corpus: List[Dict],
    max_results: int = 10,
) -> List[Dict]:
    """
    Perform a hybrid search (keyword + semantic rerank) over a Markdown corpus.

    The search process consists of two stages:

    1. Keyword filtering:
        - Documents are scanned for occurrences of query terms.
        - A short excerpt around the first match is extracted.
        - Results are ranked by keyword frequency.

    2. Semantic reranking:
        - Top-N keyword matches are reranked using cosine similarity
          between the query embedding and the full document embedding.
        - This improves relevance and reduces noise.

    Parameters
    ----------
    query : str
        The search query generated by the agent.
    corpus : List[Dict]
        A list of loaded Markdown documents (from load_markdown_files).
    max_results : int, optional
        Maximum number of results to return after reranking.

    Returns
    -------
    List[Dict]
        A list of dictionaries containing:
            - "source": file path
            - "title": file name
            - "excerpt": matched text snippet
            - "score": keyword match score
    """
    query_lower = query.lower()
    words = [w for w in query_lower.split() if w.strip()]
    results: List[Dict] = []

    if not words:
        logging.warning(f"Empty or invalid query: '{query}'")
        return []

    # --- Keyword filtering ---
    for doc in corpus:
        content = doc["content"]
        content_lower = content.lower()

        positions = [content_lower.find(w) for w in words if w in content_lower]
        positions = [p for p in positions if p >= 0]
        if not positions:
            continue

        first_pos = min(positions)
        start = max(0, first_pos - EXCERPT_BEFORE)
        end = min(len(content), start + EXCERPT_TOTAL)
        excerpt = content[start:end].strip()

        if all(w not in excerpt.lower() for w in words):
            continue

        path = doc["path"]
        title = pathlib.Path(path).name

        results.append(
            {
                "source": path,
                "title": title,
                "excerpt": excerpt,
                "score": len(positions),
            }
        )

    results.sort(key=lambda r: r["score"], reverse=True)

    results = results[:max_results]
    results = semantic_rerank(query, results, corpus, top_k=max_results)

    return results
